spring:
  application:
    name: itembankshop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: Root
    password: "123"
#    开启日志
logging:
  level:
    com.example: debug
mybatis-plus:
  type-aliases-package: com.swjd.pojo # 别名扫描包
  #mapper-locations: classpath*:/mapper/*.xml # mapper的xml文件地址
  global-config:
    db-config:
      id-type: auto # 全局主键策略，默认为自增长
      update-strategy: not_null  # 更新时，只更新非null字段
      insert-strategy: not_null  # 更新时，只更新非null字段



